import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { I18nProvider } from "@/components/providers/i18n-provider";
import { SiteChrome } from "@/components/layout/site-chrome";
import { OrganizationJsonLd } from "@/components/seo/organization-json-ld";
import { getSiteUrl } from "@/lib/site-url";

const prompt = Prompt({
  subsets: ["latin", "thai"],
  variable: "--font-prompt",
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(getSiteUrl()),
  title: {
    default: "TRS — Digital Agency",
    template: "%s | TRS",
  },
  description:
    "Modern digital agency delivering exceptional web experiences, custom software, and creative solutions.",
  keywords: ["web development", "digital agency", "design", "TRS", "custom software"],
  manifest: "/manifest.webmanifest",
  /** Favicons: generated by `app/icon.tsx` and `app/apple-icon.tsx` (no missing PNGs in `public/`). */
  icons: {
    icon: [{ url: "/icon", sizes: "32x32", type: "image/png" }],
    apple: [{ url: "/apple-icon", sizes: "180x180", type: "image/png" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" suppressHydrationWarning>
      <body className={`${prompt.variable} font-sans antialiased`}>
        <OrganizationJsonLd />
        <I18nProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <SiteChrome>{children}</SiteChrome>
          </ThemeProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
